#!/bin/sh

cd full_domain

decomposePar -force

#mpirun -np 4 moveDynamicMesh -parallel > log.moveDynamicMesh 2>&1

#mpirun -np 4 renumberMesh -overwrite -parallel > log.renumberMesh 2>&1

mpirun -np 16 overPimpleDyMFoam -parallel > log.solver 2>&1

reconstructPar

rm -rf processor*

#------------------------------------------------------------------------------
